/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimpleGUI.java
 *
 * Created on 16/Dez/2010, 22:43:12
 */
package ClientRMI2;

import ClientRMI2.StatePattern.ForbiddenActionException;
import Client_Server.Bet;
import Client_Server.Constants;
import Client_Server.Credit;
import Client_Server.Generic;
import Client_Server.Login;
import Client_Server.OnlineUsers;
import Client_Server.Message;
import Client_Server.ViewMatch;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;

/**
 *
 * @author jojo
 */
public class SimpleGUI extends GUI {

    /** Creates new form SimpleGUI */
    JRadioButton[] game = new JRadioButton[Constants.numJogos];
    javax.swing.DefaultListModel model;
    SimpleGUI m;

    public SimpleGUI() {
        model = new javax.swing.DefaultListModel();
        initComponents();
        main.setVisible(false);



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoaposta = new javax.swing.ButtonGroup();
        games = new javax.swing.ButtonGroup();
        main = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        onlineUsers = new javax.swing.JList();
        textMsg = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        JJogos = new javax.swing.JPanel();
        game0 = new javax.swing.JRadioButton();
        game1 = new javax.swing.JRadioButton();
        game2 = new javax.swing.JRadioButton();
        game3 = new javax.swing.JRadioButton();
        game4 = new javax.swing.JRadioButton();
        game5 = new javax.swing.JRadioButton();
        game6 = new javax.swing.JRadioButton();
        game7 = new javax.swing.JRadioButton();
        bet = new javax.swing.JTextField();
        apostar = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        credito = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Jogos:");

        jLabel5.setText("Chat:");

        jLabel6.setText("Onine Users");

        onlineUsers.setModel(model);
        onlineUsers.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                onlineUsersComponentAdded(evt);
            }
        });
        jScrollPane2.setViewportView(onlineUsers);

        textMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMsgActionPerformed(evt);
            }
        });

        tipoaposta.add(jRadioButton2);
        jRadioButton2.setText("Casa");
        jRadioButton2.setActionCommand("1");

        tipoaposta.add(jRadioButton3);
        jRadioButton3.setText("Empate");
        jRadioButton3.setActionCommand("0");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        tipoaposta.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("Derrota");
        jRadioButton4.setActionCommand("2");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar jogos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Actualizar users");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        chat.setColumns(20);
        chat.setEditable(false);
        chat.setRows(5);
        jScrollPane1.setViewportView(chat);

        JJogos.setLayout(new javax.swing.BoxLayout(JJogos, javax.swing.BoxLayout.PAGE_AXIS));

        games.add(game0);
        game0.setText("jRadioButton1");
        JJogos.add(game0);

        games.add(game1);
        game1.setText("jRadioButton1");
        JJogos.add(game1);

        games.add(game2);
        game2.setText("jRadioButton1");
        JJogos.add(game2);

        games.add(game3);
        game3.setText("jRadioButton1");
        JJogos.add(game3);

        games.add(game4);
        game4.setText("jRadioButton1");
        JJogos.add(game4);

        games.add(game5);
        game5.setText("jRadioButton1");
        JJogos.add(game5);

        games.add(game6);
        game6.setText("jRadioButton1");
        JJogos.add(game6);

        games.add(game7);
        game7.setText("jRadioButton1");
        JJogos.add(game7);

        apostar.setText("apostar");
        apostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostarActionPerformed(evt);
            }
        });

        name.setForeground(new java.awt.Color(0, 0, 204));
        name.setText("jLabel7");

        jButton6.setText("Actualizar credito");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel8.setText("Username:");

        credito.setForeground(new java.awt.Color(153, 255, 255));

        org.jdesktop.layout.GroupLayout mainLayout = new org.jdesktop.layout.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainLayout.createSequentialGroup()
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(mainLayout.createSequentialGroup()
                        .add(103, 103, 103)
                        .add(jLabel2)
                        .add(105, 105, 105))
                    .add(mainLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(JJogos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, mainLayout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(46, 46, 46)))
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, mainLayout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, mainLayout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(11, 11, 11))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, mainLayout.createSequentialGroup()
                        .add(textMsg)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mainLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel8)
                            .add(jButton5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(name)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(credito, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton7)
                        .add(51, 51, 51))
                    .add(mainLayout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(mainLayout.createSequentialGroup()
                                .add(username, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton1))
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6))
                        .addContainerGap(437, Short.MAX_VALUE))))
            .add(mainLayout.createSequentialGroup()
                .addContainerGap()
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mainLayout.createSequentialGroup()
                        .add(jRadioButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioButton3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioButton4))
                    .add(mainLayout.createSequentialGroup()
                        .add(bet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(apostar)))
                .addContainerGap(896, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mainLayout.createSequentialGroup()
                .addContainerGap()
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton6)
                    .add(jButton7)
                    .add(jLabel8)
                    .add(name)
                    .add(credito, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel5)
                        .add(jLabel6))
                    .add(jLabel2))
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(mainLayout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, mainLayout.createSequentialGroup()
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton5))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1)))
                    .add(mainLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(JJogos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textMsg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(username, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1)
                    .add(jButton2))
                .add(18, 18, 18)
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton2)
                    .add(jRadioButton3)
                    .add(jRadioButton4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(apostar))
                .add(205, 205, 205))
        );

        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nome:");
        Login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 61, -1, -1));

        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        Login.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 55, 125, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        Login.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 95, 125, -1));

        jLabel4.setText("Password:");
        Login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 101, 80, -1));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Login.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 97, -1));

        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Login.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Login");
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 88, 27));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(main, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 468, Short.MAX_VALUE)
                    .add(Login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 468, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(main, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 253, Short.MAX_VALUE)
                    .add(Login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 253, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        Login temp = new Login();
        temp.setName(login.getText());
        
        temp.setPassword(password.getText());
        try {
            Client.constructLoginMessage(temp);
        } catch (ForbiddenActionException ex) {
            Logger.getLogger(SimpleGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_passwordActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void textMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMsgActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Message mes = new Message();
        mes.setAuthor(Client.log.getName());
        mes.addEntry(username.getText(), textMsg.getText());
        Generic gen = new Generic();

        gen.setCode(Constants.messageCode);
        gen.setObj(mes);

        Client.gen = gen;

        Client.opt.setOption(Constants.messageCode);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Generic tempo = new Generic();
        Object temp = null;
        tempo.setObj(temp);
        Client.gen = tempo;

        Client.opt.setOption(Constants.matchesCode);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Generic tempo = new Generic();
        OnlineUsers temp = new OnlineUsers();
        tempo.setObj(temp);
        Client.gen = tempo;
        Client.opt.setOption(Constants.onlineUsersCode);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void onlineUsersComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_onlineUsersComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineUsersComponentAdded

    private void apostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apostarActionPerformed
        // TODO add your handling code here:


        Bet be = new Bet();

        be.setAposta(Integer.parseInt(tipoaposta.getSelection().getActionCommand()));
        be.setIdGame(Integer.parseInt(games.getSelection().getActionCommand()));
        be.setBet(Integer.parseInt(bet.getText()));
        try {
            Client.constructBet(be);
        } catch (ForbiddenActionException ex) {
            Logger.getLogger(SimpleGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_apostarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Client.gen.setObj(new Credit());
        Client.opt.setOption(Constants.creditCode);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        Client.opt.setOption(Constants.logoutCode);
        Client.exit = true;
        System.out.println("LOGOUT");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void game0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_game0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable()  {

            public void run() {


                SimpleGUI m = new SimpleGUI();
                m.main.setVisible(false);

                m.setVisible(true);



            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JJogos;
    private javax.swing.JPanel Login;
    private javax.swing.JButton apostar;
    private javax.swing.JTextField bet;
    private javax.swing.JTextArea chat;
    private javax.swing.JLabel credito;
    private javax.swing.JRadioButton game0;
    private javax.swing.JRadioButton game1;
    private javax.swing.JRadioButton game2;
    private javax.swing.JRadioButton game3;
    private javax.swing.JRadioButton game4;
    private javax.swing.JRadioButton game5;
    private javax.swing.JRadioButton game6;
    private javax.swing.JRadioButton game7;
    private javax.swing.ButtonGroup games;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField login;
    private javax.swing.JPanel main;
    private javax.swing.JLabel name;
    private javax.swing.JList onlineUsers;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField textMsg;
    private javax.swing.ButtonGroup tipoaposta;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displayMessage(Message m) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void treatEvent(short eventType) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void launch() {
        java.awt.EventQueue.invokeLater(new Runnable()   {

            public void run() {


                m = new SimpleGUI();
                m.main.setVisible(false);

                m.setVisible(true);



            }
        });

    }

    @Override
    public void displayMessage(String string) {

        m.chat.append(string+"\n");

    }

    @Override
    public void displayMessageString(String string) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void parseRequest(int tip, boolean stat, Object mensage) {

        switch (tip) {

            case Constants.loginCode:
                System.out.println((String) mensage);
                if (stat) {
                    System.out.println((String) mensage);
                    m.Login.setVisible(false);
                    m.main.setVisible(true);
                    m.name.setText(Client.log.getName());

                }
                break;
            case Constants.regCode:
                System.out.println((String) mensage);
                break;


            case Constants.creditCode:
                System.out.print((String)mensage);
                m.credito.setText((String)mensage);
                break;


            case Constants.matchesCode:
                displaygames((Vector<ViewMatch>) mensage);
                break;

            case Constants.betCode:
                System.out.print((String) mensage);
                break;


            case Constants.onlineUsersCode:
                model.removeAllElements();
                Vector<String> k = ((OnlineUsers) mensage).getList();
                for (int x = 0; x < k.size(); x++) {
                    model.addElement(k.elementAt(x));
                }
                m.onlineUsers.setModel(model);
                break;
                
                
                
            case Constants.logoutCode:
                System.exit(0);
                break;    
        }
    }

    private void displaygames(Vector<ViewMatch> msg) {
        //m.JJogos.setText("MMMMMMMMMMMMMMM");
        javax.swing.JRadioButton test;

        javax.swing.JRadioButton aCheckBox = new javax.swing.JRadioButton("Spinach");
        javax.swing.JButton sapo = new javax.swing.JButton("Spinach");

        for (int x = 0; x < msg.size(); x++) {
            System.out.println("[" + msg.elementAt(x).getIdJogo() + "]" + msg.elementAt(x).getHome() + " VS " + msg.elementAt(x).getFora());
            //test = new javax.swing.JRadioButton("[" + msg.elementAt(x).getIdJogo() + "]" + msg.elementAt(x).getHome() + " VS " + msg.elementAt(x).getFora());
            m.game[x].setText("[" + msg.elementAt(x).getIdJogo() + "]" + msg.elementAt(x).getHome() + " VS " + msg.elementAt(x).getFora());
            m.game[x].setActionCommand(String.valueOf(msg.elementAt(x).getIdJogo()));

            //if(x==0)
            //m.jRadioButton1.setText("[" + msg.elementAt(x).getIdJogo() + "]" + msg.elementAt(x).getHome() + " VS " + msg.elementAt(x).getFora());


        }


    }

    @Override
    public void displayMessageFrom(String from, String message) {
        m.chat.append(from + ":" + message + "\n");

    }
}
